### ISSUE TITLE
No source code is installed after installing. Has the packaged been published correctly?

### ISSUE THREAD

**Issue by justin-calleja** [dibenso/pagination-component#1]
Hi,

I only get:

* LICENSE.txt
* package.json
* README.md

After `yarn add`ing this package.

**Comment by dibenso** [comment]
Thank you for noticing that! :thumbsup: 65c291654d144d07d349a1b4554659b6e4b3fad3 fixes this issue. Version was bumped to 1.6.0 on NPM
